// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrnkmd6Yna9_kYpp_cMf-g1PqMmKQcZtM',
    appId: '1:973525837714:web:7ec381f9ad44b3fe09834b',
    messagingSenderId: '973525837714',
    projectId: 'cocktailian-app-2025',
    authDomain: 'cocktailian-app-2025.firebaseapp.com',
    storageBucket: 'cocktailian-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrVSLlHSMAjVbg3ipoQLAu-kvb5qZVwGk',
    appId: '1:973525837714:android:71f14573ffb7e9a609834b',
    messagingSenderId: '973525837714',
    projectId: 'cocktailian-app-2025',
    storageBucket: 'cocktailian-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACGmFMWGi6EbG8BnsL_08R3nt2nv-JJRw',
    appId: '1:973525837714:ios:21061c9740cbedf209834b',
    messagingSenderId: '973525837714',
    projectId: 'cocktailian-app-2025',
    storageBucket: 'cocktailian-app-2025.firebasestorage.app',
    iosBundleId: 'com.netanelk.cocktailian',
  );
}
