name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK for testing
      run: flutter build apk --debug
    
    - name: Build AAB for production
      run: flutter build appbundle
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/app/outputs/flutter-apk/app-debug.apk
          build/app/outputs/bundle/release/app-release.aab
    
    # TODO: Firebase App Distribution (requires GitHub secrets setup)
    # Uncomment when FIREBASE_APP_ID and CREDENTIAL_FILE_CONTENT secrets are added
    # - name: Deploy to Firebase App Distribution
    #   uses: wzieba/Firebase-Distribution-Github-Action@v1
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     appId: ${{ secrets.FIREBASE_APP_ID }}
    #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
    #     groups: beta-testers
    #     file: build/app/outputs/flutter-apk/app-debug.apk
    #     releaseNotes: "Automated build from commit ${{ github.sha }}"
    
    # Integration tests (when available)
    - name: Run integration tests
      run: |
        if [ -d "integration_test" ]; then
          flutter test integration_test/
        else
          echo "No integration tests found - skipping"
        fi
    
    # Test coverage reporting
    - name: Generate test coverage
      run: |
        flutter test --coverage
        genhtml coverage/lcov.info -o coverage/html
    
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
    # - name: Generate test coverage
    #   run: |
    #     flutter test --coverage
    #     genhtml coverage/lcov.info -o coverage/html
